-- Create the reports table
create table public.reports (
  id bigint generated by default as identity primary key,
  ticker text not null,
  risk_score integer,
  analysis_text text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.reports enable row level security;

-- Create policy to allow public inserts (for the admin tool usage without auth for now)
-- WARNING: In a production app with real users, you'd want authenticated inserts only.
create policy "Allow public inserts"
on public.reports
for insert
to public
with check (true);

-- Create policy to allow public read (optional, if you want to display them later)
create policy "Allow public read"
on public.reports
for select
to public
using (true);
