-- CREATE TABLE: market_summaries
-- Run this in the Supabase SQL Editor to create the table for the daily market briefings.

CREATE TABLE market_summaries (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    date date not null unique,
    title text not null,
    content text not null
);

-- Enable RLS (Row Level Security)
ALTER TABLE market_summaries ENABLE ROW LEVEL SECURITY;

-- Create Policy: "Allow public read access to market summaries"
-- This allows anyone (even unauthenticated visitors) to read the free daily summary.
CREATE POLICY "Enable read access for all users"
    ON market_summaries FOR SELECT
    USING (true);

-- Explicitly block inserts/updates from public via API (Only service role / admin allowed)
-- Service Role (used by our Vercel Cron Job) bypasses RLS automatically.
