export const tickerToDomain: Record<string, string> = {
    'NVDA': 'nvidia.com',
    'SNOW': 'snowflake.com',
    'VRT': 'vertiv.com',
    'TSLA': 'tesla.com',
    'PLTR': 'palantir.com',
    'MSFT': 'microsoft.com',
    'AAPL': 'apple.com',
    'GOOGL': 'google.com',
    'GOOG': 'google.com',
    'AMZN': 'amazon.com',
    'META': 'meta.com',
    'CRWD': 'crowdstrike.com',
    'ASML': 'asml.com',
    'AVGO': 'broadcom.com',
    'ARM': 'arm.com',
    'AMD': 'amd.com',
    'INTC': 'intel.com',
    'MU': 'micron.com',
    'QCOM': 'qualcomm.com',
    'TXN': 'ti.com',
    'ADBE': 'adobe.com',
    'CRM': 'salesforce.com',
    'NOW': 'servicenow.com',
    'SNPS': 'synopsys.com',
    'CDNS': 'cadence.com',
    'KLAC': 'kla.com',
    'LRCX': 'lamresearch.com',
    'AMAT': 'appliedmaterials.com',
    'WDC': 'westerndigital.com',
    'STX': 'seagate.com',
    'MDB': 'mongodb.com',
    'NET': 'cloudflare.com',
    'PANW': 'paloaltonetworks.com',
    'ZS': 'zscaler.com',
    'FTNT': 'fortinet.com',
    'DDOG': 'datadoghq.com',
    'SOFI': 'sofi.com',
    'AFRM': 'affirm.com',
    'HOOD': 'robinhood.com',
    'COIN': 'coinbase.com',
    'MSTR': 'microstrategy.com',
    'SMCI': 'supermicro.com',
    'UBER': 'uber.com',
    'ABNB': 'airbnb.com',
    'SQ': 'squareup.com',
    'PATH': 'uipath.com',
    'U': 'unity.com',
    'RBLX': 'roblox.com',
    'APP': 'applovin.com',
    'IOT': 'samsara.com',
};

export function getLogoUrl(ticker: string): string {
    // Return minimalist initial avatars universally based on user preference
    return `https://ui-avatars.com/api/?name=${ticker}&background=27272a&color=fff&bold=true&rounded=true`;
}
